### ISSUE TITLE
undefined method `downcase' for 0.8.1

### ISSUE THREAD

**Issue by crazymind1337** [voxpupuli/facterdb#123]
Heyho,

after the new release 0.8.1 our rspec are broken due to `undefined method `downcase'`. They have been working with 0.8.0.

```
An error occurred while loading ./spec/classes/failures_spec.rb.
Failure/Error:
  on_unsupported_os.each do |os, os_facts|
    context "with unsupported #{os}" do
      let(:facts) do
        os_facts.merge(
          'sys11_ipaddress_private' => sys11_ipaddress_private,
          'memory' => {
            'system' => {
              'total_bytes' => memory_total_bytes,
            },
          },

NoMethodError:
  undefined method `downcase' for nil:NilClass
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:268:in `describe_os'
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:251:in `block in postprocess_facts'
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:250:in `map'
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:250:in `postprocess_facts'
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:232:in `facts'
# /Users/mfroehner/.rvm/gems/ruby-2.5.5/gems/rspec-puppet-facts-unsupported-0.1.1/lib/rspec-puppet-facts-unsupported/on_unsupported_os.rb:27:in `on_unsupported_os'
# ./spec/classes/failures_spec.rb:101:in `block in <top (required)>'
# ./spec/classes/failures_spec.rb:6:in `<top (required)>'
```

Kind Regards,
Mike

**Comment by rodjek** [comment]
@crazymind1337 which fact set are you loading when this fails?

**Comment by crazymind1337** [comment]
Set environment variable to reproduce this order, for ex. on Linux `export RSPEC_PUPPET_FACTS_UNSUPPORTED_ORDER=14038`

**Comment by crazymind1337** [comment]
Set environment variable to reproduce this order, for ex. on Linux `export RSPEC_PUPPET_FACTS_UNSUPPORTED_ORDER=23334`

**Comment by crazymind1337** [comment]
We don't use a static set for unsupported facts. It is always another set and it is always failing.

**Comment by ekohl** [comment]
This is quite old by now. Is this still relevant or should it be closed?
